.gitignore, src/main/java/uk/gov/hmcts/probate/services/persistence/Application.java, src/main/java/uk/gov/hmcts/probate/services/persistence/ApplicationConfig.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberController.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberControllerTest.java
https://tools.hmcts.net/jira/browse/PRO-2409
Add an endpoint to retrieve registry sequence numbers.
```
[ ] Yes
[x] No
```
=> Pro 2409 f endpoint for sequence numbers

src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberController.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberControllerTest.java
https://tools.hmcts.net/jira/browse/PRO-2409
update url for registry sequence numbers
```
[ ] Yes
[x] No
```
=> PRO-2409: update url for registry sequence numbers

src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/model/RegistryNotConfiguredException.java, src/main/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberService.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java
https://tools.hmcts.net/jira/browse/PRO-2409
Add exception for un-configured registry
```
[ ] Yes
[x] No
```
=> PRO-2409: add exception for unconfigured registry

src/main/java/uk/gov/hmcts/probate/services/persistence/repository/FormdataRepository.java
This API endpoint will enable formdata access for re-submission in Submit Service
```
[ ] Yes
[ ] No
```
=> PRO-2656: Add findBySubmissionReference API endpoint 

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java, src/functionalTest/java/uk/gov/hmcts/probate/functional/PersistenceServiceSequenceNumberControllerTests.java, src/functionalTest/java/uk/gov/hmcts/probate/functional/TestContextConfiguration.java, src/functionalTest/java/uk/gov/hmcts/probate/functional/util/TestUtils.java, src/test/resources/application.properties
- Tests the expected behaviour of the application against the service and db
- Generates report in target folder (index.html) to illustrate test coverage
- Utilised TestUtils and TestConfiguration file which will avoid future code use as additonal tests are added
https://tools.hmcts.net/jira/browse/PRO-2797
```
[ ] Yes
[x] No
```
=>  PRO-2797: Create Functional Test suite for the Persistence Service

build.gradle, src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java, src/functionalTest/java/uk/gov/hmcts/probate/functional/PersistenceServiceSequenceNumberControllerTests.java, src/test/resources/application.properties
Remove explicit URL so it can be overriden when deployed to Azure box
- Amended application.properties to allow for this change
```
[ ] Yes
[x] No
```
=> PRO-2797: Remove explicit URL so it can be overriden when deployed to

build.gradle
https://tools.hmcts.net/jira/browse/PRO-2860
update spring boot and jdbc driver
```
[ ] Yes
[x] No
```
=> PRO-2680: Update spring boot and postgres jdbc client

build.gradle
update dependency check plugin
=> PRO-2680: update dependency check plugin

build.gradle, config/owasp/suppressions.xml
=> PRO-2680:suppress h2 warning

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, config/owasp/suppressions.xml, docker-compose.yml, infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf, liquibase.gradle, src/main/java/uk/gov/hmcts/probate/services/persistence/hibernate/JsonPostgresSQL94Dialect.java, src/main/resources/application.yml, src/main/resources/liquibase.properties
=> PRO-2073 : Move Liquibase to external task

Jenkinsfile_CNP, build.gradle, src/test/java/uk/gov/hmcts/probate/services/persistence/TestUtils.java, src/test/java/uk/gov/hmcts/probate/services/persistence/hibernate/JsonPostgresSQL94DialectTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/FormDataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/RepositoryTestConfiguration.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/TestJavaObjectSerializer.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/TestJsonDataTypeHandler.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JacksonUtilTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonBinarySqlTypeDescriptorTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonStringSqlTypeDescriptorTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonStringTypeTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/transformers/json/JsonTypeDescriptorTest.java, src/test/resources/formData.json, src/test/resources/inviteData.json, src/test/resources/submitData.json, src/test/resources/uk/gov/hmcts/probate/services/persistence/repository/submission-test.sql
- Added mutation testing config (pitest)
- Increased test coverage from about 11% to about 90%
- Embedded H2 database to test repository endpoints
- Mutations coverage increase for pitest now significant.
ONLY test code has been added.
```
[ ] Yes
[x] No
```
=> PRO-3060: Added mutation testing (pitest) and increased test coverage

build.gradle
Changed pitest dependencies to testcompile.
```
[ ] Yes
[x] No
```
=> PRO-3060: Changed pitest dependencies to testcompile.

src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SequenceNumberController.java
Added logging to sequence number controller.
```
[ ] Yes
[x] No
```
=> PRO-3060: Added logging.

build.gradle
https://tools.hmcts.net/jira/browse/PRO-3186
Do not log requests, they contain personal information
```
[ ] Yes
[x ] No
```
=> PRO-3186: do not log requests, they contain personal information

src/main/java/uk/gov/hmcts/probate/services/persistence/ApplicationConfig.java, src/main/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberService.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/RepositoryTestConfiguration.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java
https://tools.hmcts.net/jira/browse/PRO-2134
Expose table column: id for data retrieval - links to multiple execs fix
```
[ ] Yes
[ x] No
```
=> Pro 2134 f delete other exec

src/main/java/uk/gov/hmcts/probate/services/persistence/model/Formdata.java, src/main/java/uk/gov/hmcts/probate/services/persistence/model/Submission.java, src/test/java/uk/gov/hmcts/probate/services/persistence/model/FormdataTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/model/SubmissionTest.java, src/test/resources/formDataSerializationTest.json, src/test/resources/submitDataSerializationTest.json
Fixed serialization sonar bugs.
```
[ ] Yes
[X] No
```
=> PRO-3227: Fixed sonar serialization bugs.

infrastructure/main.tf, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/probate/services/persistence/model/Formdata.java, src/main/java/uk/gov/hmcts/probate/services/persistence/model/Submission.java, src/test/java/uk/gov/hmcts/probate/services/persistence/model/FormdataTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/model/SubmissionTest.java, src/test/resources/formDataSerializationTest.json, src/test/resources/submitDataSerializationTest.json
=> Pro 3227 fix sonar bugs

src/main/resources/application.yml, src/main/resources/db/changelog/db.changelog-master.yaml
https://tools.hmcts.net/jira/browse/PRO-3345
```
[ ] Yes
[x ] No
```
=> PRO-3345 : Addeded Manchester registry

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
forcing saat and sprod To use shared infra asp.
successfully built here https://sandbox-build.platform.hmcts.net/job/HMCTS/job/probate-persistence-service/job/shared_app_service_plan/build?delay=0sec
=> Shared app service plan

infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PRO-3366
```
[ ] Yes
[x ] No
```
=> [PREVIEW]  Added azure vault

infrastructure/main.tf
=> solving old vault issue in aat

infrastructure/main.tf
=> solving old valut issue in aat

infrastructure/main.tf
=> Vault correction

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/preview.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars
=> Corrected ASP and added central vault

Dockerfile, Dockerfile.github, Jenkinsfile_CNP, config/owasp/suppressions.xml, docker/entrypoint.sh, kubernetes/.lint.yml, kubernetes/config.aat.yaml, kubernetes/deployment.template.yaml
=> Added kubernetes

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PRO-4374
Suppress slf4j dependency warnings
```
[ ] Yes
[x ] No
```
=> PRO-4374: Suppression dependency check results for slf4j

build.gradle, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/probate/functional/test/IntegrationTestBase.java, src/main/java/uk/gov/hmcts/probate/services/persistence/ApplicationConfig.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/FormdataController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/InvitedataController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SubmissionController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/FormdataRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/FormdataControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/InvitedataControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SubmissionControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/FormDataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/GitCommitInfoEndpointTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java, src/test/resources/application.properties
=> Pro 4025 upgrade Spring boot libraries

build.gradle, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, infrastructure/main.tf, src/functionalTest/java/uk/gov/hmcts/probate/functional/test/IntegrationTestBase.java, src/main/java/uk/gov/hmcts/probate/services/persistence/ApplicationConfig.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/FormdataController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/InvitedataController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/controllers/SubmissionController.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/FormdataRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepository.java, src/main/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberService.java, src/main/resources/application.properties, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/FormdataControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/InvitedataControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/controllers/SubmissionControllerTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/FormDataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/repository/SubmissionRepositoryTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/GitCommitInfoEndpointTest.java, src/test/java/uk/gov/hmcts/probate/services/persistence/services/SequenceNumberServiceTest.java, src/test/resources/application.properties
=> Pro 4025 v2

Dockerfile, build.gradle
=> Update Java version

Dockerfile
PRO-4733
```
[ ] Yes
[ x] No
```
=> PRO-4733 update java

Jenkinsfile_nightly, security.sh
=> set up probate persistence service security scan

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/state.tf
=> [PREVIEW] Remove Terraform remote state

src/main/java/uk/gov/hmcts/probate/services/persistence/model/RegistryNotConfiguredException.java
https://tools.hmcts.net/jira/browse/PRO-4919
Remedy bug highlighted by Sonar Scan
```
[ ] Yes
[X] No
```
=> PRO-4919: Fix bug that Sonar Scan found

src/main/resources/db/changelog/db.changelog-master.yaml
https://tools.hmcts.net/jira/browse/PRO-4079
Update to include registry sequence for ctsc.
```
[ ] Yes
[x] No
```
=> Update database sequence for ctsc

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRO-4079
Update to add CTSC name to the registry configuration in persistence service.
```
[ ] Yes
[x] No
```
=> Adding CTSC registry ctsc to persistence config

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PRO-4079
Update to change 
```
[ ] Yes
[x] No
```
=> Update to comment out use of spring json config

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PRO-4079
Update to change 
```
[ ] Yes
[x] No
```
=> PRO-4079 Update to uncomment spring config

Jenkinsfile_CNP
=> Break pipeline to prod

src/functionalTest/java/uk/gov/hmcts/probate/functional/test/PersistenceServiceSequenceNumberControllerTests.java
=> PRO-1234: Testing for ctsc only registry fix

build.gradle, config/owasp/suppressions.xml
=> Pro 5642 upgrade owasp

README.md, config/owasp/suppressions.xml
=> test owasp

Jenkinsfile_CNP, README.md, build.gradle, config/owasp/suppressions.xml
=> rebase to demo from master

src/main/java/uk/gov/hmcts/probate/services/persistence/repository/InvitedataRepository.java
=> PRO-6602: Add new query for InviteData

src/main/java/uk/gov/hmcts/probate/services/persistence/repository/FormdataRepository.java
=> PRO-6617: Add query to restrict formdata migration

src/main/java/uk/gov/hmcts/probate/services/persistence/model/Formdata.java
=> PRO-6617: Point to view in endpoint
